env:
  name        : Phalcon
  key         : 61a89067accc701a
  cipher      : AES-256-CBC
  timezone    : UTC
  locale      : en_US
  sandbox     : false
  logs        : false
  disableView : false
  url         : http://localhost

cache:
  host  : 127.0.0.1
  port  : 6379
  db    : 0

include:
  - database
  - providers
